eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
    web-application-type: reactive

## ROUTES (PREDICATES)
  cloud:
    gateway:
      routes:
        ## Customer Service Route
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**

        ## Identity Service Route
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**

        ## Discover Server Route
        - id: discover-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        ## Discover Server Static Resources Route
        - id: discover-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**